-- This Script is Part of the Prometheus Obfuscator by Levno_710
--
-- config.lua
-- Defines global configuration variables

--------------------------------------------------
-- Project Metadata
--------------------------------------------------

local NAME     = "Prometheus"
local REVISION = "Alpha"
local VERSION  = "v0.2"
local BY       = "levno-710"

--------------------------------------------------
-- CLI Flags
--------------------------------------------------

for _, currArg in pairs(arg) do
    if currArg == "--CI" then
        local releaseName = string.gsub(
            string.format("%s %s %s", NAME, REVISION, VERSION),
            "%s",
            "-"
        )
        print(releaseName)
    end

    if currArg == "--FullVersion" then
        print(VERSION)
    end
end

--------------------------------------------------
-- Configuration
--------------------------------------------------

return {
    Name = NAME,
    NameUpper = string.upper(NAME),

    NameAndVersion = string.format("%s %s", NAME, VERSION),
    Version = VERSION,
    Revision = REVISION,

    -- Prefix used for identifiers generated by Prometheus
    -- NOTE: Scripts to be obfuscated should not already contain
    -- identifiers starting with this prefix.
    IdentPrefix = "__prometheus_",

    -- Unparser whitespace configuration
    SPACE = " ",
    TAB   = "\t"
}
